# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5322a312d2c6a53b74e4cc4d2b61240c0042edd5c996b37b6bdacc57b0c9b2ed441567189a441812dd641b27d93229a34524bcc010317420a91a8138dc84083d

test:
  secret_key_base: c5ac5a31502866f877c3bb2e8765462cee84c0d69f70c736d0692f20a387a6998d837192f961ddf4995c015042ccc2906b494a60372df35f79a3826fd042c5bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
